# Generated by Django 3.1.3 on 2020-11-17 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kimetu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')]),
        ),
    ]
