# Generated by Django 3.1.3 on 2020-11-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kimetu', '0002_auto_20201117_0219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性別')),
            ],
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性別'),
        ),
    ]
